# Site settings
title: Kevin McAlear
email: kevin.mcalear@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I love ideas, traveling, technology, wisdom, inventing, understanding systems, ultimate frisbee, leadership, wine, philosophy, humor, differences, relationships, data, & designing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kevinmcalear.com" # the base hostname & protocol for your site
twitter_username: kevinmcalear
github_username:  kevinmcalear

# Build settings
markdown: kramdown

# setting up a projects collection
collections:
  projects:
    output: true
